### ISSUE TITLE
Stuck in code view

### ISSUE THREAD

**Issue by Humanify-nl** [tomjn/Frontenberg#21]
Hi!

I love your frontenberg demo, and usually use it to demonstrate GTB for clients. Today I discovered that it seems to be stuck in the code-view mode. And I hope you'd take a look at it if you're still supporting this!

**Comment by tomjn** [comment]
Yup, I don't know why this happens, something changed in Gutenberg. Try downgrading Gutenberg, if that doesn't work then ¯\\_(ツ)\_/¯

As an aside, this repo is provided as is, you shouldn't expect everything to work smoothly

**Comment by tomjn** [comment]
related to https://github.com/WordPress/gutenberg/issues/37682

**Comment by Humanify-nl** [comment]
Yea, I assumed as such, and just wanted to notify you! I can send my clients back to the ugly official Gutenberg demo :)

**Comment by tomjn** [comment]
@Humanify-nl fixed in latest commit
