### ISSUE TITLE
Unable to run theme - undefined function get_plugin_data()

### ISSUE THREAD

**Issue by salcode** [tomjn/Frontenberg#3]
I apologize, I'm sure I'm missing something obvious.  When trying to run this site locally, I'm getting the following error.

> Fatal error: Uncaught Error: Call to undefined function get_plugin_data() in /app/public/wp-content/themes/Frontenberg/index.php on line 20

Other than adding the Gutenberg plugin, this is an unmodified Local by Flywheel installation.

Any thoughts on what I'm missing?  Once I get this sorted, I'd be happy to submit a PR for a README.md file with the information in case anyone else has the same issue.

Thanks.

![screenshot 2018-01-20 12 28 18](https://user-images.githubusercontent.com/5194588/35186158-734d8c98-fddd-11e7-8b28-87ff513596a4.png)

**Comment by tomjn** [comment]
No idea, I presume that function needs an admin file loading, but that's done in `functions.php`. I do not encounter this issue locally or in production.

Speculatively, if your WP layout is non-standard that could be a cause. Consider modifying `functions.php` where it requires at the top of the init hook to include the `plugin.php` and let me know what happens

**Comment by salcode** [comment]
@tomjn 

Thanks for your notes.  `plugin.php` was not being loaded for me, so I explicitly added to `functions.php` and now it works.

It is possible you have some other code loading `plugin.php`?  (maybe in `mu-plugins`?)

**Comment by salcode** [comment]
Investigating more closely, the `master` branch (without explicitly including `plugin.php`) works when I am **not** logged in.  However, if I am logged in, I get the "undefined function get_plugin_data() " error.

By adding the `plugin.php` explicitly, it is working for me both ways.  I'm not seeing any problems on my branch but I'm wondering if a `require_once` for `plugin.php` would be more appropriate.

**Comment by tomjn** [comment]
Interesting, can you do a PR with the change?

**Comment by tomjn** [comment]
eh I wrote too soon :) the PR's been merged
