### ISSUE TITLE
Layout options alignwide or alignfull are missing

### ISSUE THREAD

**Issue by salcode** [tomjn/Frontenberg#4]
This is a great resource - thank you.

The full-wide example is a little confusing as the layout options do not include `alignfull` even though it is being used.

![screenshot 2018-01-20 12 17 28](https://user-images.githubusercontent.com/5194588/35186048-e92512b2-fddb-11e7-930c-a654f4553f2a.png)

I suspect if we add

```
add_theme_support( 'align-wide' );
```

to `functions.php`, we can add both the `alignwide` and `alignfull` layout options.

**Comment by tomjn** [comment]
Thanks! Tested added and deployed in 2b17676
